/-
CIRISOntology.Core.RouteGauge — K1: the route → gauge operator derivation, or its
death.

VERDICT (one line): KILLED AS AN IDENTIFICATION — the decomposition of the route
Hamiltonian in the spin-1 link ladder is exact (`route_link_decomposition`), but
its gauge reading is pinned to one hand-selected representative: a route-side
physical identity (`relocate_conj`, `relocated_same_physics`) moves the Wilson
phase out of the flux-change-2 corner into the flux-change-1 hop sector, and no
Gauss-generated link gauge transformation can follow it
(`grading_is_gauge_pinned`) — so the gauge structure the map would add (which
term carries which Gauss charge, where the phase lives) is a property of the
presentation, not of the route dynamics.

THE KILL CRITERION (pre-registered: DM_GAUGE_CHEMISTRY_HANDOFF.md decisive test
#1; PROGRAM.md K1): if the map needs hand-selected operators or structure
unrelated to the route dynamics, the identification is dead. What fires it,
machine-checked:

  1. EXPRESSIBILITY IS VACUOUS. Every 3×3 complex matrix is a linear
     combination of words in the truncated ladder `U, Uᴴ` alone
     (`ladder_words_span`), so the exact decomposition of H(φ) in ladder
     operators carries no evidential weight by itself: the ladder generates the
     full matrix algebra.
  2. THE GRADING IS NOT ROUTE-INVARIANT. In the R1-pinned representative the
     phase sits entirely in the flux-change-2 corner
     (`route_link_decomposition`, `corner_commutator`). A diagonal route gauge
     move that changes NO route observable — every |amplitude| of the evolution
     is unchanged for every θ (`relocated_same_physics`), the Wilson loop is
     unchanged (`wilson_loop_invariant`) — relocates the phase into the
     flux-change-1 sector and leaves the corner bare (`relocate_conj`,
     `relocated_corner_bare`). The link side cannot follow: the gauge freedom
     generated by the electric flux operator (the Gauss flow,
     `linkGauge_is_gauss_flow`) connects the two representatives only if the
     Wilson phase is trivial (`grading_is_gauge_pinned`). "The phase is the
     Wilson angle of a charge-2 object" is therefore not a fact about route
     physics; it is a fact about one gauge-fixed matrix.
  3. NO MATTER-FREE GAUGE READING EXISTS. H(φ) has zero gauge-invariant
     (flux-preserving) component: its diagonal vanishes (`routeH_diag_zero`)
     and it never commutes with the electric flux operator (`gauss_broken`).
     Every term changes the link's Gauss charge — the tridiagonal hops by ±1
     (`ladder_commutator`), the corner by ±2 (`corner_commutator`,
     `double_raise_flux_step`); and in the spin-1 truncation the charge-2
     transporter is rank one (`linkU2_eval`), not any truncation of a unitary
     Wilson line. [The quantum-link matter-dressing argument — that a
     gauge-invariant realization of the corner needs a charge-2 matter species,
     which the one-walker route sector does not contain — is prose, NOT
     mechanized; the mechanized part is the grade arithmetic.]
  4. THE CYCLE IS NOT THE LADDER. The route sector's cyclic generator V
     (C3: V·V·V = 1) is exactly the ladder plus the wrap corner
     (`shift_eq_ladder_plus_wrap`), and NO invertible map conjugates the
     truncated ladder onto it (`ladder_not_conjugate_to_shift`: U is nilpotent,
     V is not) — the equal-dimension coincidence cannot be upgraded by any
     similarity, graded or otherwise.

WHAT SURVIVES (the exact boundary of the kill). One structure transports,
exactly: link charge conjugation (flux → −flux, `charge_conj_flips_flux`,
`charge_conj_ladder`) acts on the route Hamiltonian as time reversal
(`charge_conj_is_time_reversal`), with exact amplitude pairings at the
evolution level (`routeU_charge_conj`, `transfer_flux_reversal`,
`return_flux_reversal`) — the flux-reading face of
`RouteSymmetry.return_even`. And within the pinned chart the phase is a
link-gauge invariant (`wilson_angle_link_invariant`). Neither identifies the
carriers: both are one finite symmetry (transposition) read in two languages.

WHAT THIS FILE DOES NOT ESTABLISH. It does not kill the quantum-link lattice
programme as physics (K3/Q3 stand on their own terms); it does not touch the
matter-position reading of the route sector (a unit-charge walker on a 3-site
ring with background holonomy φ — standard minimal coupling, already the
content of `RouteSymmetry.conj_identity`), which survives precisely because it
is NOT an identification of route states with link flux states; and it does not
mechanize the matter-species argument in item 3. The consequence for the
shared-fundamental-dynamics estimate is a recorded pre-commitment in the
programme documents, not a Lean fact.

CONVERGENT ART (credited per house rule): quantum link models — Horn,
Phys.Lett.B 100:149 (1981); Orland–Rohrlich, Nucl.Phys.B 338:647 (1990);
Chandrasekharan–Wiese, Nucl.Phys.B 492:455 (1997). Gauge fields on graphs and
lattice walks as credited in `RouteSymmetry`. The decomposition-by-charge is
the standard weight-grading of a U(1) action; nothing here is claimed as new
mathematics — the theorems mechanize the verdict on OUR map.
-/
import CIRISOntology.Core.RouteSymmetry
import CIRISOntology.Core.DMGauge

namespace CIRISOntology.Core.RouteGauge

open Matrix Complex
open CIRISOntology.Core.RouteSymmetry
open CIRISOntology.Core.DMGauge

noncomputable section

/-- `Complex.abs` form of `RouteSymmetry.norm_ph`. -/
theorem abs_ph (x : ℝ) : Complex.abs (ph x) = 1 := by
  simpa [Complex.norm_eq_abs] using norm_ph x

/-! ### The link algebra, as matrices on the route carrier -/

/-- The electric flux operator `E = diag(−1,0,1)` — `DMGauge.flux` as a matrix. -/
def linkE : Matrix (Fin 3) (Fin 3) ℂ := Matrix.diagonal ![-1, 0, 1]

/-- The truncated spin-1 raising operator — `DMGauge.raise` as a matrix:
`U|−1⟩ = |0⟩`, `U|0⟩ = |+1⟩`, `U|+1⟩ = 0`. -/
def linkU : Matrix (Fin 3) (Fin 3) ℂ := !![0, 0, 0; 1, 0, 0; 0, 1, 0]

/-- The double raise `U²` — the corner of the route Hamiltonian. -/
def linkU2 : Matrix (Fin 3) (Fin 3) ℂ := linkU * linkU

/-- `U²` is the rank-one transition `|−1⟩ ↦ |+1⟩`: in the spin-1 truncation the
charge-2 transporter is not any truncation of a unitary Wilson line. -/
theorem linkU2_eval : linkU2 = !![0, 0, 0; 0, 0, 0; 1, 0, 0] := by
  unfold linkU2 linkU
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.mul_apply, Fin.sum_univ_three, Matrix.vecHead, Matrix.vecTail]

/-- `linkE` is `DMGauge.flux`, entry for entry. -/
theorem linkE_matches_flux (q : FluxState) : linkE q q = (flux q : ℂ) := by
  fin_cases q <;> simp [linkE, flux, Matrix.diagonal]

/-- `linkU` acts exactly as `DMGauge.raise` wherever the latter is defined. -/
theorem linkU_matches_raise {q q' : FluxState} (h : raise q = some q') :
    linkU q' q = 1 := by
  fin_cases q
  · simp only [raise, Option.some.injEq] at h
    subst q'; simp [linkU]
  · simp only [raise, Option.some.injEq] at h
    subst q'; simp [linkU]
  · simp [raise] at h

/-- `linkU` annihilates the top flux state, matching `raise ⟨2⟩ = none`. -/
theorem linkU_annihilates_top (i : Fin 3) : linkU i 2 = 0 := by
  fin_cases i <;> rfl

/-! ### Grade arithmetic: what Gauss charge each term carries -/

/-- `[E, U] = U`: the ladder raises electric flux by one — the matrix face of
`DMGauge.raise_flux_step`. -/
theorem ladder_commutator : linkE * linkU - linkU * linkE = linkU := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [linkE, linkU, Matrix.mul_apply, Fin.sum_univ_three, Matrix.diagonal,
      Matrix.sub_apply, Matrix.vecHead, Matrix.vecTail]

/-- `[E, U²] = 2·U²`: the corner is a flux-change-2 operator. In a U(1)
quantum-link model this is a charge-2 insertion, NOT a magnetic (plaquette)
term — plaquette moves preserve every Gauss charge
(`DMGauge.plaquette_raise_preserves_gauss`). -/
theorem corner_commutator :
    linkE * linkU2 - linkU2 * linkE = (2 : ℂ) • linkU2 := by
  rw [linkU2_eval]
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [linkE, Matrix.mul_apply, Fin.sum_univ_three, Matrix.diagonal,
      Matrix.sub_apply, Matrix.smul_apply, Matrix.vecHead, Matrix.vecTail,
      Fin.ext_iff]

/-- The combinatorial face of the corner's grade: two raises change
`DMGauge.flux` by exactly two. -/
theorem double_raise_flux_step {q q' q'' : FluxState}
    (h1 : raise q = some q') (h2 : raise q' = some q'') :
    flux q'' - flux q = 2 := by
  have s1 := raise_flux_step h1
  have s2 := raise_flux_step h2
  omega

/-! ### 1. The decomposition identity — VERIFIED -/

/-- **The identity behind the proposed map, verified.** The route Hamiltonian is
the bare ladder hop plus the phase-dressed double raise:
`H(φ) = (U + Uᴴ) + (e^{iφ}·U² + e^{−iφ}·(U²)ᴴ)`.
Exact — and, by `ladder_words_span` below, exactly as evidential as any 3×3
identity in the ladder algebra: not at all, on its own. -/
theorem route_link_decomposition (φ : ℝ) :
    routeH φ = (linkU + linkUᴴ) + (ph φ • linkU2 + ph (-φ) • linkU2ᴴ) := by
  rw [linkU2_eval]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [routeH, linkU, Matrix.add_apply, Matrix.smul_apply,
      Matrix.conjTranspose_apply, Matrix.vecHead, Matrix.vecTail, smul_eq_mul]

/-! ### 2. The vacuousness fence: the ladder generates everything -/

theorem unit02 : linkU2ᴴ = !![0, 0, 1; 0, 0, 0; 0, 0, 0] := by
  rw [linkU2_eval]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.conjTranspose_apply, Matrix.vecHead, Matrix.vecTail]

theorem unit00 : linkU2ᴴ * linkU2 = !![1, 0, 0; 0, 0, 0; 0, 0, 0] := by
  rw [unit02, linkU2_eval]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.mul_apply, Fin.sum_univ_three, Matrix.vecHead, Matrix.vecTail]

theorem unit22 : linkU2 * linkU2ᴴ = !![0, 0, 0; 0, 0, 0; 0, 0, 1] := by
  rw [unit02, linkU2_eval]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.mul_apply, Fin.sum_univ_three, Matrix.vecHead, Matrix.vecTail]

theorem unit11 : (linkUᴴ * linkU) * (linkU * linkUᴴ) = !![0, 0, 0; 0, 1, 0; 0, 0, 0] := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [linkU, Matrix.mul_apply, Matrix.vecMul, Matrix.dotProduct,
      Fin.sum_univ_three, Matrix.conjTranspose_apply,
      Matrix.vecHead, Matrix.vecTail]

theorem unit01 : (linkU2ᴴ * linkU2) * linkUᴴ = !![0, 1, 0; 0, 0, 0; 0, 0, 0] := by
  rw [unit00]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [linkU, Matrix.mul_apply, Fin.sum_univ_three, Matrix.conjTranspose_apply,
      Matrix.vecHead, Matrix.vecTail]

theorem unit10 : linkU * (linkU2ᴴ * linkU2) = !![0, 0, 0; 1, 0, 0; 0, 0, 0] := by
  rw [unit00]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [linkU, Matrix.mul_apply, Fin.sum_univ_three, Matrix.vecHead, Matrix.vecTail]

theorem unit12 : ((linkUᴴ * linkU) * (linkU * linkUᴴ)) * linkUᴴ
    = !![0, 0, 0; 0, 0, 1; 0, 0, 0] := by
  rw [unit11]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [linkU, Matrix.mul_apply, Fin.sum_univ_three, Matrix.conjTranspose_apply,
      Matrix.vecHead, Matrix.vecTail]

theorem unit21 : linkU * ((linkUᴴ * linkU) * (linkU * linkUᴴ))
    = !![0, 0, 0; 0, 0, 0; 0, 1, 0] := by
  rw [unit11]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [linkU, Matrix.mul_apply, Fin.sum_univ_three, Matrix.vecHead, Matrix.vecTail]

/-- **The vacuousness fence.** Every 3×3 complex matrix is a linear combination
of words in the truncated ladder `U, Uᴴ` alone (recall `linkU2 = linkU * linkU`
definitionally): the ladder generates the full matrix algebra, so "H(φ) is
expressible in the link algebra" is true of EVERY Hamiltonian and is not
evidence for the route → gauge identification. -/
theorem ladder_words_span (M : Matrix (Fin 3) (Fin 3) ℂ) :
    M = M 0 0 • (linkU2ᴴ * linkU2)
      + M 0 1 • ((linkU2ᴴ * linkU2) * linkUᴴ)
      + M 0 2 • linkU2ᴴ
      + M 1 0 • (linkU * (linkU2ᴴ * linkU2))
      + M 1 1 • ((linkUᴴ * linkU) * (linkU * linkUᴴ))
      + M 1 2 • (((linkUᴴ * linkU) * (linkU * linkUᴴ)) * linkUᴴ)
      + M 2 0 • linkU2
      + M 2 1 • (linkU * ((linkUᴴ * linkU) * (linkU * linkUᴴ)))
      + M 2 2 • (linkU2 * linkU2ᴴ) := by
  rw [unit01, unit12, unit10, unit21, unit00, unit11, unit22, unit02, linkU2_eval]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.add_apply, Matrix.smul_apply, smul_eq_mul,
      Matrix.vecHead, Matrix.vecTail]

/-! ### 3. What transports: link charge conjugation = route time reversal -/

/-- Charge conjugation on the flux basis: `|q⟩ ↦ |−q⟩`. -/
def Cconj : Matrix (Fin 3) (Fin 3) ℂ := !![0, 0, 1; 0, 1, 0; 1, 0, 0]

theorem Cconj_mul_Cconj : Cconj * Cconj = 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Cconj, Matrix.mul_apply, Fin.sum_univ_three, Matrix.one_apply,
      Matrix.vecHead, Matrix.vecTail]

/-- `Cconj` as a unit (it is an involution). -/
def CconjUnit : (Matrix (Fin 3) (Fin 3) ℂ)ˣ :=
  ⟨Cconj, Cconj, Cconj_mul_Cconj, Cconj_mul_Cconj⟩

/-- `Cconj` really is charge conjugation: it flips the electric flux. -/
theorem charge_conj_flips_flux : Cconj * linkE * Cconj = -linkE := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Cconj, linkE, Matrix.mul_apply, Fin.sum_univ_three, Matrix.diagonal,
      Matrix.neg_apply, Matrix.vecHead, Matrix.vecTail]

/-- Charge conjugation carries the raising ladder to the lowering ladder. -/
theorem charge_conj_ladder : Cconj * linkU * Cconj = linkUᴴ := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Cconj, linkU, Matrix.mul_apply, Fin.sum_univ_three,
      Matrix.conjTranspose_apply, Matrix.vecHead, Matrix.vecTail]

/-- Flux conjugation acts on the route Hamiltonian as `φ → −φ`. -/
theorem charge_conj_routeH (φ : ℝ) : Cconj * routeH φ * Cconj = routeH (-φ) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Cconj, routeH, Matrix.mul_apply, Fin.sum_univ_three, neg_neg,
      Matrix.vecHead, Matrix.vecTail]

/-- **The one principled transport**: link charge conjugation is route time
reversal (`RouteSymmetry.routeH_transpose`). This is one finite symmetry read
in two languages; it does not identify the carriers. -/
theorem charge_conj_is_time_reversal (φ : ℝ) :
    Cconj * routeH φ * Cconj = (routeH φ)ᵀ := by
  rw [charge_conj_routeH, routeH_transpose]

/-- The conjugation at the evolution level. -/
theorem routeU_charge_conj (θ φ : ℝ) :
    Cconj * routeU θ φ * Cconj = routeU θ (-φ) := by
  unfold routeU
  have h1 : Cconj * NormedSpace.exp ℂ ((-(θ : ℂ) * Complex.I) • routeH φ) * Cconj
      = NormedSpace.exp ℂ (Cconj * ((-(θ : ℂ) * Complex.I) • routeH φ) * Cconj) := by
    have := (Matrix.exp_units_conj ℂ CconjUnit ((-(θ : ℂ) * Complex.I) • routeH φ)).symm
    simpa [CconjUnit] using this
  have h2 : Cconj * ((-(θ : ℂ) * Complex.I) • routeH φ) * Cconj
      = (-(θ : ℂ) * Complex.I) • routeH (-φ) := by
    rw [Matrix.mul_smul, Matrix.smul_mul, charge_conj_routeH]
  rw [h1, h2]

/-- Entry extraction: `(C M C)₀₂ = M₂₀`. -/
theorem Cconj_entry02 (M : Matrix (Fin 3) (Fin 3) ℂ) :
    (Cconj * M * Cconj) 0 2 = M 2 0 := by
  simp [Cconj, Matrix.mul_apply, Matrix.vecMul, Matrix.dotProduct,
    Fin.sum_univ_three, Matrix.vecHead, Matrix.vecTail]

/-- Entry extraction: `(C M C)₀₀ = M₂₂`. -/
theorem Cconj_entry00 (M : Matrix (Fin 3) (Fin 3) ℂ) :
    (Cconj * M * Cconj) 0 0 = M 2 2 := by
  simp [Cconj, Matrix.mul_apply, Matrix.vecMul, Matrix.dotProduct,
    Fin.sum_univ_three, Matrix.vecHead, Matrix.vecTail]

/-- Exact amplitude pairing: the flux-reversed transfer at reversed loop phase.
The gauge-language face of `RouteSymmetry.transfer_chirality`'s sector. -/
theorem transfer_flux_reversal (θ φ : ℝ) :
    routeU θ (-φ) 0 2 = routeU θ φ 2 0 := by
  rw [← routeU_charge_conj, Cconj_entry02]

/-- Exact amplitude pairing for returns: flux-conjugate returns pair across
`φ → −φ` — the gauge-language face of `RouteSymmetry.return_even`. -/
theorem return_flux_reversal (θ φ : ℝ) :
    routeU θ (-φ) 0 0 = routeU θ φ 2 2 := by
  rw [← routeU_charge_conj, Cconj_entry00]

/-! ### 4. No matter-free gauge reading -/

/-- The gauge-invariant (flux-preserving, grade-0) component of the route
Hamiltonian is zero: its diagonal vanishes identically. -/
theorem routeH_diag_zero (φ : ℝ) (i : Fin 3) : routeH φ i i = 0 := by
  fin_cases i <;> simp [routeH]

/-- The route Hamiltonian never commutes with the electric flux operator: read
as a matter-free single-link operator it violates the Gauss law at every φ. -/
theorem gauss_broken (φ : ℝ) : linkE * routeH φ ≠ routeH φ * linkE := by
  intro h
  have h10 := congrArg (fun M => M 1 0) h
  simp [linkE, routeH, Matrix.mul_apply, Fin.sum_univ_three, Matrix.diagonal,
    Matrix.vecHead, Matrix.vecTail] at h10

/-! ### 5. THE KILL: the grading is pinned to a hand-selected representative -/

/-- The route-side diagonal gauge move `g(φ) = diag(e^{iφ},1,1)`. -/
def gRel (φ : ℝ) : Matrix (Fin 3) (Fin 3) ℂ := Matrix.diagonal ![ph φ, 1, 1]

def gRelInv (φ : ℝ) : Matrix (Fin 3) (Fin 3) ℂ := Matrix.diagonal ![ph (-φ), 1, 1]

theorem gRel_mul_gRelInv (φ : ℝ) : gRel φ * gRelInv φ = 1 := by
  unfold gRel gRelInv
  rw [Matrix.diagonal_mul_diagonal]
  have h : (fun i => ![ph φ, 1, 1] i * ![ph (-φ), 1, 1] i) = fun _ => (1 : ℂ) := by
    funext i; fin_cases i <;> simp
  rw [h, Matrix.diagonal_one]

theorem gRelInv_mul_gRel (φ : ℝ) : gRelInv φ * gRel φ = 1 := by
  unfold gRel gRelInv
  rw [Matrix.diagonal_mul_diagonal]
  have h : (fun i => ![ph (-φ), 1, 1] i * ![ph φ, 1, 1] i) = fun _ => (1 : ℂ) := by
    funext i; fin_cases i <;> simp
  rw [h, Matrix.diagonal_one]

/-- `gRel φ` as a unit. -/
def gRelUnit (φ : ℝ) : (Matrix (Fin 3) (Fin 3) ℂ)ˣ :=
  ⟨gRel φ, gRelInv φ, gRel_mul_gRelInv φ, gRelInv_mul_gRel φ⟩

/-- The relocated representative: same route physics, phase on the 0–1 edge,
corner bare. -/
def routeH' (φ : ℝ) : Matrix (Fin 3) (Fin 3) ℂ :=
  !![0, ph φ, 1; ph (-φ), 0, 1; 1, 1, 0]

/-- The route gauge move relocates the phase: `g H(φ) g⁻¹ = H'(φ)`. -/
theorem relocate_conj (φ : ℝ) : gRel φ * routeH φ * gRelInv φ = routeH' φ := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [gRel, gRelInv, routeH, routeH', Matrix.mul_apply, Fin.sum_univ_three,
      Matrix.diagonal, Matrix.vecHead, Matrix.vecTail]

/-- In the R1-pinned representative the hops are bare and the corner carries
the whole phase. -/
theorem pinned_corner_phased (φ : ℝ) :
    routeH φ 2 0 = ph φ ∧ routeH φ 1 0 = 1 ∧ routeH φ 2 1 = 1 := by
  refine ⟨?_, ?_, ?_⟩ <;> simp [routeH]

/-- In the relocated representative the corner is bare and the phase sits in
the flux-change-1 hop sector: the "charge-2 Wilson angle" has changed grade
under a transformation that changes no route observable. -/
theorem relocated_corner_bare (φ : ℝ) :
    routeH' φ 2 0 = 1 ∧ routeH' φ 0 2 = 1 ∧ routeH' φ 1 0 = ph (-φ) := by
  refine ⟨?_, ?_, ?_⟩ <;> simp [routeH']

/-- The Wilson loop (the route side's only gauge-invariant phase content) is
unchanged by the relocation. -/
theorem wilson_loop_invariant (φ : ℝ) :
    routeH' φ 1 0 * routeH' φ 2 1 * routeH' φ 0 2
      = routeH φ 1 0 * routeH φ 2 1 * routeH φ 0 2 := by
  simp [routeH, routeH']

/-- The relocation changes NO route observable: every amplitude modulus of the
evolution generated by `H'(φ)` equals the corresponding `routeU` modulus, for
every θ and every entry. The two representatives are the SAME route physics. -/
theorem relocated_same_physics (θ φ : ℝ) (i j : Fin 3) :
    ‖NormedSpace.exp ℂ ((-(θ : ℂ) * Complex.I) • routeH' φ) i j‖
      = ‖routeU θ φ i j‖ := by
  have hU : routeU θ φ = NormedSpace.exp ℂ ((-(θ : ℂ) * Complex.I) • routeH φ) := rfl
  have hA : (-(θ : ℂ) * Complex.I) • routeH' φ
      = gRel φ * ((-(θ : ℂ) * Complex.I) • routeH φ) * gRelInv φ := by
    rw [Matrix.mul_smul, Matrix.smul_mul, relocate_conj]
  have hexp : NormedSpace.exp ℂ
        (gRel φ * ((-(θ : ℂ) * Complex.I) • routeH φ) * gRelInv φ)
      = gRel φ * NormedSpace.exp ℂ ((-(θ : ℂ) * Complex.I) • routeH φ) * gRelInv φ := by
    have := Matrix.exp_units_conj ℂ (gRelUnit φ) ((-(θ : ℂ) * Complex.I) • routeH φ)
    simpa [gRelUnit] using this
  rw [hA, hexp, hU]
  fin_cases i <;> fin_cases j <;>
    simp [gRel, gRelInv, Matrix.mul_apply, Fin.sum_univ_three, Matrix.diagonal,
      Matrix.vecHead, Matrix.vecTail, norm_mul, abs_ph]

/-- The single-link gauge group: the flow generated by the Gauss charge,
`Λ(α) = e^{iαE} = diag(e^{−iα}, 1, e^{iα})`. -/
def linkGauge (α : ℝ) : Matrix (Fin 3) (Fin 3) ℂ :=
  Matrix.diagonal ![ph (-α), 1, ph α]

def linkGaugeInv (α : ℝ) : Matrix (Fin 3) (Fin 3) ℂ :=
  Matrix.diagonal ![ph α, 1, ph (-α)]

/-- `linkGauge` IS the exponential of the electric flux operator — the gauge
flow the Gauss law generates on one link, not a hand-chosen family. -/
theorem linkGauge_is_gauss_flow (α : ℝ) :
    NormedSpace.exp ℂ (((α : ℂ) * Complex.I) • linkE) = linkGauge α := by
  unfold linkE linkGauge
  rw [← Matrix.diagonal_smul, Matrix.exp_diagonal]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.diagonal, Pi.smul_apply, smul_eq_mul, ← Complex.exp_eq_exp_ℂ,
      ph, Complex.ofReal_neg, neg_mul, mul_neg_one, mul_neg,
      Matrix.vecHead, Matrix.vecTail]

/-- **THE KILL.** The two representatives of the same route physics are
connected by a link gauge transformation only if the Wilson phase is trivial:
for `e^{iφ} ≠ 1`, NO Gauss-generated gauge move carries `H(φ)` (phase on the
corner, grade 2) to `H'(φ)` (phase on the hop, grade 1). The flux-grading of
the route Hamiltonian — the entire gauge content the proposed map would add —
is therefore not a function of the route dynamics: it is pinned to the
hand-selected R1 representative, and the pre-registered kill criterion fires. -/
theorem grading_is_gauge_pinned (φ α : ℝ)
    (h : linkGauge α * routeH φ * linkGaugeInv α = routeH' φ) : ph φ = 1 := by
  have h21 := congrArg (fun M => M 2 1) h
  have h10 := congrArg (fun M => M 1 0) h
  simp [linkGauge, linkGaugeInv, routeH, routeH', Matrix.mul_apply,
    Fin.sum_univ_three, Matrix.diagonal, Matrix.vecHead, Matrix.vecTail] at h21 h10
  -- h21 : ph α = 1;  h10 : ph α = ph (−φ)
  rw [h21] at h10
  have hφ := ph_mul_neg φ
  rw [← h10, mul_one] at hφ
  exact hφ

/-- Within the pinned chart, the phase is a link-gauge invariant: the Gauss
flow cannot change it (complementing the kill: route gauge moves it freely,
link gauge cannot move it at all — the two gauge structures are incompatible). -/
theorem wilson_angle_link_invariant (φ ψ α : ℝ)
    (h : linkGauge α * routeH φ * linkGaugeInv α = routeH ψ) : ph φ = ph ψ := by
  have h21 := congrArg (fun M => M 2 1) h
  have h20 := congrArg (fun M => M 2 0) h
  simp [linkGauge, linkGaugeInv, routeH, Matrix.mul_apply,
    Fin.sum_univ_three, Matrix.diagonal, Matrix.vecHead, Matrix.vecTail] at h21 h20
  -- h21 : ph α = 1;  h20 : ph α * ph φ * ph α = ph ψ  (up to arrangement)
  rw [h21] at h20
  simpa using h20

/-! ### 6. The cycle is not the ladder -/

/-- The route sector's cyclic generator: `V|0⟩=|1⟩, V|1⟩=|2⟩, V|2⟩=|0⟩`. -/
def cyclicShift : Matrix (Fin 3) (Fin 3) ℂ := !![0, 0, 1; 1, 0, 0; 0, 1, 0]

/-- The C3 cycle is the A3 ladder plus the wrap corner, exactly: the corner
term is not decoration on the map — it is the entire difference between the
two structures. -/
theorem shift_eq_ladder_plus_wrap : cyclicShift = linkU + linkU2ᴴ := by
  rw [unit02]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [cyclicShift, linkU, Matrix.add_apply, Matrix.vecHead, Matrix.vecTail]

theorem shift_cubed : cyclicShift * cyclicShift * cyclicShift = 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [cyclicShift, Matrix.mul_apply, Fin.sum_univ_three, Matrix.one_apply,
      Matrix.vecHead, Matrix.vecTail]

theorem ladder_cubed : linkU * linkU * linkU = 0 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [linkU, Matrix.mul_apply, Fin.sum_univ_three, Matrix.vecHead, Matrix.vecTail]

/-- **No similarity, graded or otherwise**: the truncated ladder is nilpotent,
the cyclic shift is invertible, so no invertible map conjugates one onto the
other (`T = S⁻¹` recovers the similarity statement; only `T * S = 1` is even
needed). The equal-dimension coincidence between the route carrier and the
spin-1 link cannot be upgraded to an algebra identification by any change of
basis. -/
theorem ladder_not_conjugate_to_shift
    (S T : Matrix (Fin 3) (Fin 3) ℂ) (hTS : T * S = 1) :
    S * linkU * T ≠ cyclicShift := by
  intro h
  have key : ∀ A B : Matrix (Fin 3) (Fin 3) ℂ,
      (S * A * T) * (S * B * T) = S * (A * B) * T := by
    intro A B
    calc (S * A * T) * (S * B * T)
        = S * (A * ((T * S) * (B * T))) := by simp only [Matrix.mul_assoc]
      _ = S * (A * (B * T)) := by rw [hTS, Matrix.one_mul]
      _ = S * (A * B) * T := by simp only [Matrix.mul_assoc]
  have h3 : cyclicShift * cyclicShift * cyclicShift
      = S * (linkU * linkU * linkU) * T := by
    rw [← h, key, key]
  rw [ladder_cubed, Matrix.mul_zero, Matrix.zero_mul, shift_cubed] at h3
  have h00 := congrArg (fun M => M 0 0) h3
  simp [Matrix.one_apply] at h00

end

end CIRISOntology.Core.RouteGauge
