//! The Z2xZ2 character sectors — the object's conserved charges.
//!
//! The automorphism group of the eleven kinds is order 4 (`Symmetry.aut_with_stack`),
//! generated by the two twin swaps [`crate::TWINS`] = (Priorities, Process) and
//! (Structure, Circumstances). Being Z2xZ2, it has four one-dimensional characters,
//! and the state space splits as a direct sum of their eigenspaces:
//!
//! ```text
//!   sector 0  (+,+)   dim 9   both twins symmetric      — the "bright" sector
//!   sector 1  (+,-)   dim 1   twin 1 antisymmetric      — the (Structure, Circumstances) dark mode
//!   sector 2  (-,+)   dim 1   twin 0 antisymmetric      — the (Priorities, Process)     dark mode
//!   sector 3  (-,-)   dim 0   both antisymmetric        — EMPTY
//! ```
//!
//! The two one-dimensional sectors ARE the dark modes: each is spanned by a single
//! [`dark_vector`]. The (-,-) sector is empty because the two swaps act on disjoint
//! index pairs, so no basis vector is odd under both — it is a real structural fact
//! about the object, not a numerical accident, and [`sector_dims`] is the place it is
//! visible.
//!
//! ## Why the sectors are the conservation law
//!
//! A coupling matrix that commutes with the group is block-diagonal across the
//! sectors: no dynamics can move amplitude between them, so sector occupancy is
//! conserved for all time. [`inter_sector_leakage`] is the diagnostic for exactly
//! that, and it is the quantity that separates the two matrices a [`Structure`]
//! carries: `coupling_sym` is block-diagonal to machine zero, while the MEASURED
//! `coupling` is not — at `N = 11` it leaks at ~4.51, which is a measurement about the
//! object and not an error to be cleaned up.
//!
//! ## At other `N`
//!
//! Nothing above is specific to eleven nodes. Any structure carrying two disjoint twin
//! transpositions has the same four characters, and [`build_projectors`] constructs
//! them by averaging over the group. A structure with no twins
//! ([`crate::structure::NO_TWINS`]) has dimensions `[N, 0, 0, 0]`: everything is
//! bright, there are no dark modes, and the diagnostics below still run and read zero.

use crate::structure::{permute, Structure};

/// Number of Z2xZ2 character sectors.
pub const SECTORS: usize = 4;

/// `1/sqrt(2)`, the normalisation of a two-node antisymmetric mode. Taken from `core`
/// rather than computed, so no `libm` call and no rounding enters the dark vector.
const INV_SQRT2: f64 = core::f64::consts::FRAC_1_SQRT_2;

/// The character of group element `(m0, m1)` in sector `s`.
///
/// Sectors are ordered `(+,+) (+,-) (-,+) (-,-)`, so the sign under the FIRST twin is
/// the high bit of `s` and the sign under the second is the low bit.
#[inline]
fn character(s: usize, m0: bool, m1: bool) -> f64 {
    let mut chi = 1.0f64;
    if m0 && s >= 2 {
        chi = -chi;
    }
    if m1 && (s & 1) == 1 {
        chi = -chi;
    }
    chi
}

/// Build the four character projectors from two twin transpositions.
///
/// `P_s = (1/4) sum_g chi_s(g) rho(g)`, the standard character projection onto an
/// irreducible of an abelian group. A transposition of an index with itself is the
/// identity, so an absent generator needs no special case: the two characters odd in
/// it project onto nothing and their sectors come out empty, which is the right
/// answer.
///
/// Every entry is a sum of four copies of `+-1/4`, so the result is exact in binary
/// floating point — the projectors are rationals, not approximations, at any `N`.
///
/// The two transpositions must be DISJOINT. They generate Z2xZ2 only if they commute,
/// and overlapping transpositions generate S3 instead, for which four one-dimensional
/// characters do not exist and the output would be meaningless.
pub fn build_projectors<const N: usize>(
    twins: &[(usize, usize); 2],
) -> [[[f64; N]; N]; SECTORS] {
    let mut p = [[[0.0f64; N]; N]; SECTORS];
    for s in 0..SECTORS {
        for j in 0..N {
            for g in 0..4 {
                let m0 = (g & 1) == 1;
                let m1 = (g & 2) == 2;
                let i = permute(j, twins, m0, m1);
                p[s][i][j] += 0.25 * character(s, m0, m1);
            }
        }
    }
    p
}

/// Sector dimensions read off the projector traces, which is what a projector's trace
/// is: the dimension of the space it projects onto.
///
/// Rounded to the nearest integer because the trace is an exact small rational and any
/// departure from an integer would be rounding, not information.
pub fn sector_dims_from_projectors<const N: usize>(
    p: &[[[f64; N]; N]; SECTORS],
) -> [usize; SECTORS] {
    let mut dims = [0usize; SECTORS];
    for s in 0..SECTORS {
        let mut tr = 0.0f64;
        for i in 0..N {
            tr += p[s][i][i];
        }
        let r = libm::round(tr);
        dims[s] = if r > 0.0 { r as usize } else { 0 };
    }
    dims
}

/// Dimensions of the four character sectors — `[9, 1, 1, 0]` for the built-in object.
///
/// They sum to `N` because the four characters exhaust the group.
pub fn sector_dims<const N: usize>(st: &Structure<N>) -> [usize; SECTORS] {
    st.sector_dims
}

/// Project `v` onto character `sector` using the structure's projectors.
///
/// The four projections of any vector sum back to that vector, since the projectors
/// resolve the identity.
///
/// # Panics
/// If `sector >= 4`.
pub fn project<const N: usize>(st: &Structure<N>, v: &[f64; N], sector: usize) -> [f64; N] {
    assert!(sector < SECTORS, "sector index out of range");
    let p = &st.sector_projectors[sector];
    let mut out = [0.0f64; N];
    for i in 0..N {
        let mut acc = 0.0f64;
        for j in 0..N {
            acc += p[i][j] * v[j];
        }
        out[i] = acc;
    }
    out
}

/// The normalised dark vector of a twin pair: `d = (e_a - e_b)/sqrt(2)` for
/// `(a, b) = st.twins[twin]`.
///
/// This is `DarkState.dark` up to normalisation. Under a coupling that is symmetric
/// in the pair it is an exact eigenvector with eigenvalue `-c_ab`
/// (`DarkState.twin_dark_state`), and every other row annihilates it
/// (`DarkState.dark_state_decoupled`) — which is what [`crate::twin_probe::probe`]
/// exercises.
///
/// The sign convention is `+` on the first member of the pair. Both signs span the
/// same sector, so the choice is cosmetic; it is fixed here so results replay
/// bit-identically.
///
/// An absent twin (`a == b`) has no antisymmetric mode and returns the zero vector,
/// which is the honest answer rather than a unit vector in a space of dimension zero.
///
/// # Panics
/// If `twin >= 2`.
pub fn dark_vector<const N: usize>(st: &Structure<N>, twin: usize) -> [f64; N] {
    assert!(twin < st.twins.len(), "twin index out of range");
    let (a, b) = st.twins[twin];
    let mut d = [0.0f64; N];
    if a != b {
        d[a] = INV_SQRT2;
        d[b] = -INV_SQRT2;
    }
    d
}

/// Matrix product, fixed loop order so the float accumulation is deterministic.
fn mul<const N: usize>(a: &[[f64; N]; N], b: &[[f64; N]; N]) -> [[f64; N]; N] {
    let mut out = [[0.0f64; N]; N];
    for i in 0..N {
        for j in 0..N {
            let mut acc = 0.0f64;
            for k in 0..N {
                acc += a[i][k] * b[k][j];
            }
            out[i][j] = acc;
        }
    }
    out
}

/// The conservation diagnostic: `max |P_a M P_b|` over all entries and all ordered
/// sector pairs `a != b`.
///
/// Zero means `M` commutes with the twin group, so sector occupancy is conserved
/// exactly and each dark mode evolves on its own forever. Nonzero is the rate at
/// which the sectors talk to each other.
///
/// Measured on the built-in object's two matrices:
///
/// ```text
///   coupling_sym   0        (block-diagonal by construction)
///   coupling       4.508…   (entry [2][6] of the (+,+)-(+,-) block:
///                            Manner couples to Structure at 9.016 and to
///                            Circumstances at 0 — that whole asymmetry
///                            lands in the dark sector)
/// ```
///
/// Cost is `O(N^3)` per sector pair. This is a diagnostic, not a per-step quantity.
pub fn inter_sector_leakage<const N: usize>(st: &Structure<N>, m: &[[f64; N]; N]) -> f64 {
    let mut worst = 0.0f64;
    for a in 0..SECTORS {
        let pm = mul(&st.sector_projectors[a], m);
        for b in 0..SECTORS {
            if a == b {
                continue;
            }
            let block = mul(&pm, &st.sector_projectors[b]);
            for i in 0..N {
                for j in 0..N {
                    let v = libm::fabs(block[i][j]);
                    if v > worst {
                        worst = v;
                    }
                }
            }
        }
    }
    worst
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::structure::{Structure, K11, NO_TWINS};
    use crate::tables;
    use crate::N;

    #[test]
    fn sector_dims_are_nine_one_one_zero() {
        assert_eq!(sector_dims(&K11), [9, 1, 1, 0]);
        assert_eq!(sector_dims(&K11).iter().sum::<usize>(), N);
    }

    /// The dimensions are the projector traces, so the shipped table cannot disagree
    /// with the shipped projectors without this failing. Kept concrete at `N = 11`:
    /// it is a check on `tables.rs`, which exists only at that size.
    #[test]
    fn sector_dims_are_the_projector_traces() {
        for s in 0..SECTORS {
            let mut tr = 0.0f64;
            for i in 0..N {
                tr += tables::SECTOR_PROJECTORS[s][i][i];
            }
            assert!(
                libm::fabs(tr - tables::SECTOR_DIMS[s] as f64) < 1e-12,
                "sector {s}: trace {tr} != dim {}",
                tables::SECTOR_DIMS[s]
            );
        }
    }

    /// The four projectors resolve the identity: every vector is the sum of its
    /// four sector components.
    #[test]
    fn projectors_resolve_the_identity() {
        let v: [f64; N] = [1.0, -2.0, 3.5, 0.25, -7.0, 11.0, 0.5, -0.5, 2.0, -3.0, 13.0];
        let mut sum = [0.0f64; N];
        for s in 0..SECTORS {
            let p = project(&K11, &v, s);
            for i in 0..N {
                sum[i] += p[i];
            }
        }
        for i in 0..N {
            assert!(libm::fabs(sum[i] - v[i]) < 1e-12, "component {i}");
        }
    }

    /// Each dark vector is a unit vector living entirely inside its own
    /// one-dimensional sector: twin 0 in sector 2 (-,+), twin 1 in sector 1 (+,-).
    #[test]
    fn dark_vectors_span_the_one_dimensional_sectors() {
        for (twin, own) in [(0usize, 2usize), (1, 1)] {
            let d = dark_vector(&K11, twin);
            let norm_sq: f64 = d.iter().map(|x| x * x).sum();
            assert!(libm::fabs(norm_sq - 1.0) < 1e-15, "twin {twin} not normalised");
            for s in 0..SECTORS {
                let p = project(&K11, &d, s);
                let residual: f64 = if s == own {
                    (0..N).map(|i| libm::fabs(p[i] - d[i])).fold(0.0, f64::max)
                } else {
                    (0..N).map(|i| libm::fabs(p[i])).fold(0.0, f64::max)
                };
                assert!(residual < 1e-15, "twin {twin} sector {s}: residual {residual}");
            }
        }
    }

    #[test]
    fn symmetrised_coupling_conserves_the_sectors() {
        let leak = inter_sector_leakage(&K11, &K11.coupling_sym);
        assert!(leak < 1e-12, "coupling_sym leaked {leak}, expected machine zero");
    }

    /// The measured coupling does NOT conserve them, and the size of the violation
    /// is a measurement — CIRISOntology reads it at ~4.51.
    #[test]
    fn measured_coupling_leaks_across_sectors() {
        let leak = inter_sector_leakage(&K11, &K11.coupling);
        assert!(leak > 1.0, "coupling leaked only {leak}, expected ~4.51");
        assert!(
            libm::fabs(leak - 4.508_157_515_13) < 1e-9,
            "coupling leakage {leak}, expected 4.508157515"
        );
    }

    /// The sector machinery is not a table lookup: at an `N` the tables do not cover,
    /// the projectors still resolve the identity, the dimensions still sum to `N`, and
    /// a coupling built to be twin-symmetric still conserves the sectors exactly.
    #[test]
    fn sectors_work_at_other_sizes() {
        // Four nodes, twins (0,1) and (2,3), coupled so that the symmetry is exact.
        let c = [
            [0.0, 5.0, 2.0, 2.0],
            [5.0, 0.0, 2.0, 2.0],
            [2.0, 2.0, 0.0, 7.0],
            [2.0, 2.0, 7.0, 0.0],
        ];
        let st = Structure::<4>::from_coupling(&c, [(0, 1), (2, 3)]);
        assert_eq!(sector_dims(&st).iter().sum::<usize>(), 4);
        // Each twin pair contributes one bright and one dark dimension, and no basis
        // vector is odd under both swaps, so (-,-) is empty here for exactly the
        // reason it is empty at N = 11.
        assert_eq!(sector_dims(&st), [2, 1, 1, 0]);

        let v = [1.0, -2.0, 3.0, 0.5];
        let mut sum = [0.0f64; 4];
        for s in 0..SECTORS {
            let p = project(&st, &v, s);
            for i in 0..4 {
                sum[i] += p[i];
            }
        }
        for i in 0..4 {
            assert!(libm::fabs(sum[i] - v[i]) < 1e-14, "component {i}");
        }

        // This coupling is already twin-symmetric, so it must conserve the sectors.
        let leak = inter_sector_leakage(&st, &st.coupling);
        assert!(leak < 1e-12, "an exactly symmetric coupling leaked {leak}");
    }

    /// With no twins the group is trivial: one sector of full dimension, and the
    /// bright projector is the identity.
    #[test]
    fn no_twins_gives_one_full_sector() {
        let c = [[0.0, 1.0, 0.0], [1.0, 0.0, 1.0], [0.0, 1.0, 0.0]];
        let st = Structure::<3>::from_coupling(&c, NO_TWINS);
        assert_eq!(sector_dims(&st), [3, 0, 0, 0]);
        for i in 0..3 {
            for j in 0..3 {
                let want = if i == j { 1.0 } else { 0.0 };
                assert_eq!(st.sector_projectors[0][i][j], want);
                for s in 1..SECTORS {
                    assert_eq!(st.sector_projectors[s][i][j], 0.0);
                }
            }
        }
        assert_eq!(dark_vector(&st, 0), [0.0; 3]);
    }
}
