#!/usr/bin/env python3
"""Build AXIOM_TABLE.md from the before/after enumeration dumps."""
import re, glob, collections, sys

BEFORE = 'scratchpad/axiom_enum.out'
AFTER  = 'scratchpad/axiom_enum_final.out'

def source_decls():
    files = sorted(glob.glob('CIRISOntology/Core/*.lean')) + ['CIRISOntology/Stance.lean']
    files = [f for f in files if 'NonFactoring' not in f]
    decl = {}
    for f in files:
        ns = []
        for i, ln in enumerate(open(f).read().split('\n'), 1):
            m = re.match(r'^(\s*)namespace\s+([A-Za-z_][\w.\']*)', ln)
            if m: ns.append(m.group(2)); continue
            m = re.match(r'^(\s*)end\s+([A-Za-z_][\w.\']*)\s*$', ln)
            if m and ns and ns[-1] == m.group(2): ns.pop(); continue
            m = re.match(r"^\s*(?:@\[[^\]]*\]\s*)?(?:private\s+|protected\s+|nonrec\s+)*(theorem|lemma)\s+([A-Za-z_][\w.'!?]*)", ln)
            if m:
                priv = 'private' in ln.split(m.group(1))[0]
                decl['.'.join(ns + [m.group(2)])] = (f, i, priv)
    return decl

def load(p):
    e = {}
    for ln in open(p):
        q = ln.rstrip('\n').split('\t')
        if len(q) < 3: continue
        e[q[2]] = (q[1], frozenset(a for a in (q[3] if len(q) > 3 else '').split(',') if a))
    return e

def cls(axs):
    if not axs: return 'axiom-free'
    if 'Classical.choice' in axs: return 'all three'
    return 'no choice: ' + ' + '.join(sorted(x.replace('Classical.', '') for x in axs))

decl, before, after = source_decls(), load(BEFORE), load(AFTER)
pub = {k: v for k, v in decl.items() if k in after and not v[2]}

cb, ca = collections.Counter(), collections.Counter()
permod = collections.defaultdict(lambda: collections.Counter())
changed, kept = [], []
for k, (f, l, _) in pub.items():
    b = cls(before[k][1]) if k in before else '(new)'
    a = cls(after[k][1])
    cb[b] += 1; ca[a] += 1
    permod[f][a] += 1
    if b != a: changed.append((f, l, k, b, a))
    if after[k][1] and 'Classical.choice' not in after[k][1]:
        kept.append((f, l, k, a))

out = []
w = out.append
w('# Axiom dependency audit — CIRISOntology Lean library\n')
w('Generated by `scratchpad/mk_table.py` from `#print axioms` over every public')
w('`theorem`/`lemma` in `CIRISOntology/Core/*.lean` and `CIRISOntology/Stance.lean`.')
w('`Core/NonFactoring.lean` is excluded (owned by another pass).')
w('Private lemmas are excluded; a `sorry` or exotic axiom in one is still caught,')
w('because `collectAxioms` is transitive and every private lemma has a public consumer.\n')
w(f'**Total public theorems: {len(pub)}**\n')
w('| axiom class | before | after |')
w('|---|---:|---:|')
for k in ['axiom-free', 'no choice: propext', 'no choice: Quot.sound + propext', 'all three']:
    if cb[k] or ca[k]: w(f'| {k} | {cb[k]} | {ca[k]} |')
for k in sorted(set(cb) | set(ca)):
    if k not in ['axiom-free', 'no choice: propext', 'no choice: Quot.sound + propext', 'all three']:
        w(f'| {k} | {cb[k]} | {ca[k]} |')
w(f'| **total** | **{sum(cb.values())}** | **{sum(ca.values())}** |')
w('')
w('## Per module, after\n')
w('| module | axiom-free | propext and/or Quot.sound | all three |')
w('|---|---:|---:|---:|')
for f in sorted(permod):
    c = permod[f]
    mid = sum(v for kk, v in c.items() if kk.startswith('no choice'))
    w(f'| `{f.split("/")[-1]}` | {c["axiom-free"]} | {mid} | {c["all three"]} |')
w('')
w(f'## Proofs rewritten this pass ({len(changed)})\n')
w('Statements are untouched; only proofs changed.\n')
w('| file:line | theorem | before | after |')
w('|---|---|---|---|')
for f, l, k, b, a in sorted(changed):
    w(f'| `{f}:{l}` | `{k.split(".")[-1]}` | {b} | {a} |')
w('')
REASONS = {
 'updBit_eq_update':
   '`funext` (which IS `Quot.sound`) plus `Function.update_apply` (`propext`). Irreducible: the statement is an equality of functions.',
 'sgnZ_mul_self':
   'the DEFINITION `sgnZ` carries `propext` through its `if`; no proof mentioning `sgnZ` can be free of it.',
 'signF_sum':
   '`decide` over `Finset.sum`; `Finset` is a quotient of `List`, so `Quot.sound` is structural.',
 'scan_nodup':
   '`List.Pairwise.map` (`propext`, `Quot.sound`) and `List.filter_sublist` (`propext`).',
 'availableSites_mono':
   '`List.mem_filter` (`propext`) and `List.elem_eq_true_of_mem` / `List.mem_of_elem_eq_true` (`propext`).',
 'scan_mono':
   '`List.map_subset` (`propext`, `Quot.sound`), plus `availableSites_mono` above.',
 'scan_le_full': 'inherited from `scan_mono`.',
 'availableSites_univ':
   '`List.filter_eq_self` (`propext`, `Quot.sound`).',
 'scan_terminal': 'inherited from `availableSites_univ`.',
 'scan_terminal_card': 'inherited from `scan_terminal`.',
 'carriers_in_every_scan': 'inherited from `scan_mono`.',
}

w('## Why the 345 cannot move\n')
w('Every one of them is a statement about `Real`. Mathlib builds `Real` as a quotient of')
w('Cauchy sequences (`Quot.sound`) and gives it a `LinearOrder` whose decidability is')
w('`Classical.dec` (`Classical.choice`). The floor is visible in Mathlib itself:')
w('`#print axioms Real.mul_pos` already reports all three. No proof stated over `Real`,')
w('however elementary, can be axiom-free, so this is a property of the ambient library')
w('and not of anything in this repository. The same holds for the handful whose')
w('statements hide `Real` behind a definition (`IsProb`, `IsKernel`, `samePairs`,')
w('`signSymmetric`) — all of those are `Real`-valued predicates.\n')
w(f'## Still carrying an axiom without Classical.choice ({len(kept)}), with the reason\n')
w('| file:line | theorem | axioms | what forces it |')
w('|---|---|---|---|')
for f, l, k, a in sorted(kept):
    short = k.split(".")[-1]
    w(f'| `{f}:{l}` | `{short}` | {a} | {REASONS.get(short, "—")} |')
w('')
w('The eight `Scan.lean` entries are one cluster: they are the theorems that go through')
w('Mathlib\'s `List` API for `filter`, `map` and `Sublist`. Freeing them means reproving')
w('that API inline, which trades a documented `propext` for a page of list induction, so')
w('they are left as they are and recorded here.\n')

w('## Audit wiring\n')
w('`Audit/AxiomAudit.lean` gained, this pass:\n')
w('- **336 assert lines** (168 theorems x `assert_no_sorry` + `assert_standard_axioms`)')
w('  covering the six modules that had never been named there (`WrongKind`, `Generator`,')
w('  `Instrument`, `Confront`, `Scan`, `Stack`) plus the partly-covered analytic modules')
w('  (`Share`, `ShareQuantum`, `EntropyIneq`, `BellCeiling`, `HammingCap`, `Intensive`).')
w('- **The enumeration gate, section (2b)**: a `run_cmd` that asks the ENVIRONMENT for')
w('  every theorem the library declares instead of reading a list, and applies both')
w('  tests to each. It covers private and compiler-generated declarations too. One')
w('  shared traversal, so it costs ~5s where the equivalent 850 `collectAxioms` calls')
w('  cost ~3m20s. This is the part that cannot go stale.')
w('- **27 exact `#guard_msgs` pins** for the newly axiom-free theorems, plus 3 stale')
w('  pins corrected — `parityRepair_not_percell`, `majorityRepair_not_percell` and')
w('  `bool_const_of_eq` were pinned at `[propext]` and are now free. Without a pin a')
w('  later `simp` would silently restore the axiom and no other gate would notice.\n')
w('Cost: the audit file elaborates in roughly 10 minutes (9m41s measured with the new')
w('assert lines in place, before the gate and the pins were added). The hand lists')
w('dominate that — `collectAxioms` re-walks the whole transitive closure on every call,')
w('about 0.65s each. The enumeration gate subsumes sections (1) and (2) at 5 seconds')
w('total, so trimming the lists would take the audit under a minute. That is a call for')
w('the steward, not for this pass; CI sets no job timeout, so 10 minutes does not break')
w('anything today.\n')
open('scratchpad/AXIOM_TABLE.md', 'w').write('\n'.join(out) + '\n')
print(f'wrote scratchpad/AXIOM_TABLE.md — {len(pub)} theorems, {len(changed)} rewritten, {len(kept)} non-free non-choice')
print('before:', dict(cb))
print('after :', dict(ca))
