ITEMS = {
 "dim_task": ("ISO dimension: Task", "dialogue acts that move the task or activity forward which motivates the dialogue"),
 "dim_autofeedback": ("ISO dimension: Auto-Feedback", "providing/eliciting information about the current speaker's processing of previous utterances"),
 "dim_allofeedback": ("ISO dimension: Allo-Feedback", "the same, about the current addressee's processing of previous utterances"),
 "dim_turn": ("ISO dimension: Turn Management", "obtaining, keeping, releasing, or assigning the right to speak"),
 "dim_time": ("ISO dimension: Time Management", "managing the use of time in the interaction"),
 "dim_discourse": ("ISO dimension: Discourse Structuring", "topic management, opening/closing (sub-)dialogues, otherwise structuring the dialogue"),
 "dim_owncm": ("ISO dimension: Own Communication Management", "the speaker editing their own current contribution"),
 "dim_partnercm": ("ISO dimension: Partner Communication Management", "the speaker editing another current speaker's contribution"),
 "dim_socialobl": ("ISO dimension: Social Obligations Management", "greeting, self-introduction, apologizing, thanking"),
 "extra_contact": ("DIT++ dimension: Contact Management", "establishing and maintaining contact and attention"),
 "extra_taskmgmt": ("DAMSL dimension: Task Management", "discussing or explaining a task as opposed to moving it forward"),
 "qual_certainty": ("Qualifier: certainty", "a qualifier expressing that a dialogue act is performed with un-certainty (certainty or uncertainty)"),
 "qual_conditionality": ("Qualifier: conditionality", "a qualifier expressing that a dialogue act is performed conditionally"),
 "qual_sentiment": ("Qualifier: sentiment", "a qualifier expressing that a dialogue act is performed with a particular sentiment"),
 "rel_funcdep": ("Structural device: functional dependence relation", "a semantic relation between dialogue acts indicating which question is answered by a certain answer act"),
 "rel_feeddep": ("Structural device: feedback dependence relation", "a semantic relation indicating which utterance a feedback act responds to"),
 "rel_rhetorical": ("Structural device: rhetorical relation", "a relation annotated to indicate for example that one dialogue act explains the performance of another dialogue act"),
}
